DROP TABLE IF EXISTS books;

CREATE TABLE books(
    BOOKID SERIAL PRIMARY KEY NOT NULL,
    TITLE   VARCHAR(255),
    AUTHORS ARRAY,
    AVERAGE_RATING FLOAT,
    ISBN VARCHAR(10),
    ISBN13 VARCHAR(13),
    LANGUAGE_CODE VARCHAR(20),
    NUM_PAGES SMALLINT,
    RATINGS_COUNT BIGINT,
    TEXT_REVIEWS_COUNT BIGINT,
    PUBLICATION_DATE DATE,
    PUBLISHER VARCHAR(255)
);